### PR TITLE
refactor: make it easier to fetch upstream changes

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/celestiaorg/celestia-core/issues/1504 by deleting a bunch of files that we don't need to maintain in this fork.

### CODE REVIEW

**Review by evan-forbes — DISMISSED** [review]

**Review by rach-id — APPROVED** [review]
+15 −10,259 :tada:

**Comment by rootulp** [comment]
CI is failing :(

**Review by cmwaters — DISMISSED** [review]
I don't mind merging this because I don't think any of this is relevant but I'm curious, does this actually make it easier to fetch upstream changes?

**Review by rach-id — APPROVED** [review]

**Review by rach-id — APPROVED** [review]

**Review by cmwaters — COMMENTED** [review]
Happy to merge this but I think we should keep the celestia ADRs

**Comment by rootulp** [comment]
Great catch!

**Review by evan-forbes — APPROVED** [review]

**Review by cmwaters — APPROVED** [review]

**Review by Magkoooh — APPROVED** [review]

**Pull request merged**
