### PR TITLE
Reset celestia-core to tendermint master

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

This PR is like hitting the reset button and eliminating all merge conflicts with tendermint master.

steps taken:
- make a commit to delete everything
- merge tendermint master and accept all of the their changes
- copy and paste the missing pieces

this PR **does not** have any celestia-core specific code yet, we still have to copy paste that back in

Closes: #XXX

### CODE REVIEW

**Comment by liamsi** [comment]
How did this commit come into existence? https://github.com/celestiaorg/celestia-core/commit/fcca94a24bc107df0bcbc6b53a488671cba7fd98
Copy from where?

**Comment by evan-forbes** [comment]
> How did this commit come into existence? fcca94a

due to merging process taken in this PR, deleting everything, then merging, there were a lot of missing files at the end. So I deleted everything again and then copy and pasted the entire tendermint directory back in.

this approach is probably not the best, but at the time I was just experimenting to try and save git histories while also resetting to tendermint master.

**Comment by liamsi** [comment]
I can confirm that this branch as per 
is on par with tendermint's [b0684bd300af59fbc73e4a5d0881ace1f821bf2c](https://github.com/tendermint/tendermint/commit/b0684bd300af59fbc73e4a5d0881ace1f821bf2c).

Let's re-apply (ideally cherry-pick?) all the changes we want to this branch in separate PRs.

**Comment by evan-forbes** [comment]
closing in favor of #534

**Pull request closed without merging**
