### PR TITLE
Reset to tendermint master

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

This PR uses `git merge -s ours` to essentially reset this repo to tendermint master. This serves the same purpose as #527 but in a way less hacky way, and doesn't mess up the git blame. 

Keeping as a draft for now, as we will be cherry-picking the parts of celestia-core that we want to keep into this PR, almost as a temporary `master` branch

closes: #538, #512, #505, #492
completes the majority of #528

### CODE REVIEW

**Review by liamsi — COMMENTED** [review]
I think we are missing a few ADRs? Or did you skip that last ones intentionally? The last one in here is ad4-004.
I would recommend diffing the changes to the last upstream commit this PR is based on (namely [ad067d73b96bb1b5f958828f9368e827864f49eb](https://github.com/tendermint/tendermint/commit/ad067d73b96bb1b5f958828f9368e827864f49eb)). 
Locally that is easy, if you want to share that diff with others you can create a fork of tendermint, and submit a draft-pr on your fork with this branch.

**Comment by liamsi** [comment]
Posted a full diff here: https://gist.github.com/liamsi/77abeecdece89afb5039d77263210894

**Comment by evan-forbes** [comment]
Definitely did not mean to leave out the ADRs, nice catch! 

went ahead and pull the most recent changes from tendermint master, along following @liamsi's advice to create a PR that hopefully makes it easier to view the changes introduced in this PR ref #551 

planning on rebasing to clean up git history a bit more when we are closer to merging

**Comment by liamsi** [comment]
Thanks for adding the missing ADRs and creating the diff view on your fork!

why does this commit contain so many changes?
https://github.com/celestiaorg/celestia-core/pull/534/commits/eac8f84117fb7878050469c465a793078a05b403

**Comment by liamsi** [comment]
> planning on rebasing to clean up git history a bit more when we are closer to merging

BTW, after looking at the diff a bit more thoroughly, I think we can merge this very soon!

**Comment by liamsi** [comment]
So, this looks good to me. the only question I have is why does https://github.com/celestiaorg/celestia-core/pull/534/commits/1bb8ddc557dec930c09284eb1a5949e4aa4d7c4a show up instead of: https://github.com/celestiaorg/celestia-core/commit/cf7537ea5f8306c60df4e5dab39e0686d390117a  / the changes of https://github.com/tendermint/tendermint/pull/6975?

**Comment by evan-forbes** [comment]
> So, this looks good to me. the only question I have is why does 1bb8ddc show up instead of: cf7537e / the changes of tendermint/tendermint#6975?

I think I accidentally changed the name of one of the merges from upstream because I ran `go mod tidy` afterwords, and then altered the title of the merge commit to reflect that. Either that messed github up, or made git think it was me introducing all of the changes instead of preserving the git history like a normal merge.

I have redone the most recent pull from upstream and not altered the title of the commit, which seems to fix it.

thanks again for catching that!

**Review by liamsi — APPROVED** [review]
OK, let's merge this beast of a PR :muscle:

**Pull request merged**
