### PR TITLE
chore: cleanup go.mod file require sections

### PR DESCRIPTION
**Pull request by Jorropo**
This PR does not change any of the dependency, it only reorders the go.mod file into a direct and undirect import section, as go versions do since 1.17.

The reason your go.mod file got so many require sections is because during the 1.16 to 1.17 go.mod styling transition you had different contributors updating the go.mod file with pre 1.17 and post 1.17 releases of go.

See https://go.dev/doc/modules/gomod-ref:
> At go 1.17 or higher:

section for a description of what changed.

### CODE REVIEW

**Comment by Jorropo** [comment]
Similar https://github.com/celestiaorg/celestia-node/pull/3103

**Review by rootulp — APPROVED** [review]
Thanks for your PR! Similar to https://github.com/celestiaorg/celestia-app/pull/2892

We could also do this on this branch: https://github.com/celestiaorg/celestia-core/blob/v0.34.x-celestia/go.mod

**Review by ninabarbakadze — DISMISSED** [review]
thanks!

**Review by evan-forbes — APPROVED** [review]
we just need to fix the conflict @Jorropo

**Comment by Jorropo** [comment]
@evan-forbes done

**Review by rootulp — APPROVED** [review]

**Review by ninabarbakadze — APPROVED** [review]

**Review by evan-forbes — APPROVED** [review]

**Comment by rootulp** [comment]
I think this repo doesn't allow merges if the branch is out-of-date with the base branch. IMO we should disable that. If we want to keep that setting one, we should look into merge queues.

Screenshot 2024-01-30 at 1 08 08 PM

**Review by evan-forbes — APPROVED** [review]

**Comment by rootulp** [comment]
Oh lol maybe we can't merge this PR b/c we don't have 2 CODEOWNER approvals? https://github.com/celestiaorg/celestia-core/blob/40ee792bb2f878dfaba02f352c4951386eb59883/.github/CODEOWNERS#L10

I don't have permission to see the settings on this repo so IDK what's actually configured

**Review by cmwaters — APPROVED** [review]

**Comment by rootulp** [comment]
This PR is an enigma. Why can't it merge?

Screenshot 2024-02-06 at 10 12 26 AM

**Review by evan-forbes — APPROVED** [review]

**Review by evan-forbes — APPROVED** [review]

**Comment by evan-forbes** [comment]
maybe we just need to merge main

**Pull request merged**
