### PR TITLE
fix specs links

### PR DESCRIPTION
**Pull request by SweeXordious**
Fixes the specs links across the repo.
Closes https://github.com/celestiaorg/celestia-core/issues/805

### CODE REVIEW

**Review by evan-forbes — COMMENTED** [review]
we should point this at the v0.34 branch (and change the default back)

**Comment by SweeXordious** [comment]
@evan-forbes good now?

**Comment by evan-forbes** [comment]
wait, this is probably something else, but why is the CI not running?

**Comment by SweeXordious** [comment]
I don't have  enough permissions to trigger  them. Are you able to?

**Review by evan-forbes — APPROVED** [review]

**Pull request merged**
