### PR TITLE
bug: failing test for bug found in block 825320 on devnet-2

### PR DESCRIPTION
**Pull request by tzdybal**

### CODE REVIEW

**Comment by tzdybal** [comment]
Related https://github.com/celestiaorg/celestia-node/issues/621

**Comment by liamsi** [comment]
What is the status of this?

**Comment by evan-forbes** [comment]
> What is the status of this?

bump @tzdybal 

I think we can close?

**Comment by tzdybal** [comment]
Somehow missed previous bump ;)
This PR should be closed.

**Pull request closed without merging**
