### PR TITLE
update rsmt2d 03.1 -> 0.4.0

### PR DESCRIPTION
**Pull request by liamsi**
update to rsmt2d 0.4.0

### CODE REVIEW

**Comment by liamsi** [comment]
Needs fixing:

 - [ ] Docker build is failing as the docker image does not seem to have gcc installled
 - [ ] e2e tests are failing because `/usr/bin/ld: cannot find -llibleopard`
 - [ ] test coverage on arm is failing because: `# runtime/cgo
gcc: error: unrecognized command line option '-marm'; did you mean '-mabm'?`

**Comment by adlerjohn** [comment]
How was it working before????

**Comment by liamsi** [comment]
> How was it working before????

I think we changed some tests to also use leopard in rsmt2d? Still surprising as it is only tests.

**Comment by liamsi** [comment]
> # runtime/cgo
> gcc: error: unrecognized command line option '-marm'; did you mean '-mabm'?

Is arm a must-have at all?

**Review by adlerjohn — APPROVED** [review]

**Comment by liamsi** [comment]
OK, so the reason for the failures were that we bumped go to 1.17  [here](https://github.com/celestiaorg/rsmt2d/pull/76/commits/068d9e30706fa1fe1c0b1aadd6b4757999c8c78d) including the build tag without keeping the backwards compatibility like previously [in here](https://github.com/celestiaorg/rsmt2d/commit/9c00b79df4d4c58cbae7f14309728ce8dde0ab80) for instance. This forces us to update the whole repo to go1.17 here as well. (which IMO is good to do anyways).

**Pull request merged**
