### PR TITLE
fix: catch context errors from http provider

### PR DESCRIPTION
**Pull request by cmwaters**
## Description

It seems from attemption to perform state sync that the light client is not correctly detecting when the context gets cancelled or the deadline is exceeded as the error is being wrapped

```
[90m12:53PM[0m [32mINF[0m error from light block request from primary, removing... [36merror=[0m[31m"post failed: Post \"https://rpc-snapscale.lunaroasis.net:443\": context deadline exceeded"[0m [36mheight=[0m354290 [36mmodule=[0mlight [36mprimary=[0m{}
```

This PR checks to see if `context deadline exceeded` is contained within the error and then returns the actual context error

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use
  [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Review by evan-forbes — DISMISSED** [review]

**Comment by rootulp** [comment]
[not blocking] just curious, why is the text encoding broken in the error message in the PR description? Is there an issue for that already?

**Comment by rootulp** [comment]
[question] why does golangci-lint fail [here](https://github.com/celestiaorg/celestia-core/actions/runs/7259368180/job/19776362237?pr=1160#step:5:27) for unrelated changes? Do we need a new issue for that?

**Review by rootulp — DISMISSED** [review]
Is it possible to include a unit test so that we don't introduce a regression to this behavior when we pull from upstream?

**Comment by evan-forbes** [comment]
> why does golangci-lint fail [here](https://github.com/celestiaorg/celestia-core/actions/runs/7259368180/job/19776362237?pr=1160#step:5:27) for unrelated changes?

ahhhhhhhhhhh

**Comment by cmwaters** [comment]
> Is it possible to include a unit test so that we don't introduce a regression to this behavior when we pull from upstream?

Yeah I can look into that

**Review by rootulp — APPROVED** [review]

**Review by evan-forbes — APPROVED** [review]

**Pull request merged**
