### PR TITLE
Delete celestia-logo.png

### PR DESCRIPTION
**Pull request by rootulp**
This logo was previously used in the README but it's no longer used

### CODE REVIEW

**Comment by evan-forbes** [comment]
should we put the logo somewhere instead? fine with either, especially since this isn't a library that others will import

**Review by evan-forbes — APPROVED** [review]
approving, but pls see comment

**Comment by rootulp** [comment]
It seemed odd to be located in `docs/celestia-architecture/`  so this question makes sense:

> should we put the logo somewhere instead?

I sampled a few other READMEs in celestiaorg and don't see the logo used so opted to remove for consistency with other repos. I'm not sure where else this logo asset makes sense to display in this repo but open to adding it back if we want it displayed somewhere.

**Comment by evan-forbes** [comment]
cool that makes sense

**Pull request merged**
