### PR TITLE
breaking!: move share consts to celestia-app

### PR DESCRIPTION
**Pull request by rootulp**
## Description

Closes https://github.com/celestiaorg/celestia-core/issues/841
Opens https://github.com/celestiaorg/celestia-app/pull/709

### CODE REVIEW

**Review by evan-forbes — COMMENTED** [review]
[blocking question]
shouldn't we also move the rest as well?

I think the only ones that we can't are TxNamespaceID and DataCommitmentBlocksLimit

**Comment by evan-forbes** [comment]
I'd also be ok with moving those constants to the only spots that they're used, then move the entire consts package to the app

**Comment by rootulp** [comment]
> I think the only ones that we can't are NewBaseHash, TxNamespaceID and DataCommitmentBlocksLimit

+1

> I'd also be ok with moving those constants to the only spots that they're used, then move the entire consts package to the app

It seems slightly preferable to preserve these three in `consts.go` rather than inlining them (to ease moving them later). Will move the consts that aren't used in celestia-core in an upcoming commit

**Review by evan-forbes — APPROVED** [review]
noice! also, agree with not moving the file, that makes sense.

pre-approving, but let's obvi wait for CI just in case

**Comment by rootulp** [comment]
btw thanks for disabling merge commits! No more accidental merges

Screen Shot 2022-09-14 at 5 48 18 PM

**Pull request merged**
