### PR TITLE
Revert writing to IPLD during defaultDecideProposal

### PR DESCRIPTION
**Pull request by liamsi**
Closes: #436

### CODE REVIEW

**Comment by Wondertan** [comment]
LGTM, though I feel like this should break something unless we do PutBlock elsewhere, don't remember exactly/

**Comment by evan-forbes** [comment]
@Wondertan I think `PutBlock` is called when saving the block after it is finalized

https://github.com/lazyledger/lazyledger-core/blob/3ba47c2dd58042cd07d3ac740d7fc2ab54fdab9b/consensus/state.go#L1595-L1595

**Comment by liamsi** [comment]
@Wondertan if this would break something how would nodes that do not propose work properly?

**Comment by liamsi** [comment]
Surprisingly, `TestWriteDiscoveryReadData` times out 🤔 It's not directly related to the code happening during proposal. I'm glad we are moving this out of this repo.

**Comment by Wondertan** [comment]
@evan-forbes, ok, so we merged that PR with blockstore updates. We have so many unfinished PRs in the repo that I lost track of what is merged and what is not. Hopefully, in the new repo, changes will land much quicker 🤞🏻

**Review by Wondertan — APPROVED** [review]

**Comment by liamsi** [comment]
Speaking of open PRs. Do you mind addressing the suggestion in https://github.com/celestiaorg/celestia-core/pull/434 so we can merge it?

**Comment by liamsi** [comment]
rebased on master

**Pull request merged**
