### PR TITLE
test(mempool/cat): fix flaky TestTxPool_BroadcastQueue

### LINKED ISSUE #1261: Flake in `TestTxPool_BroadcastQueue`
See https://github.com/celestiaorg/celestia-core/actions/runs/8210249540/job/22457347611?pr=1260
```
--- FAIL: TestTxPool_BroadcastQueue (0.00s)
    pool_test.go:755: 
        	Error Trace:	/home/runner/work/celestia-core/celestia-core/mempool/cat/pool_test.go:755
        	            				/opt/hostedtoolcache/go/1.22.1/x64/src/runtime/asm_amd64.s:1695
        	Error:      	Not equal: 
        	            	expected: types.Tx{0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2d, 0x30, 0x30, 0x30, 0x2d, 0x30, 0x3d, 0x33, 0x31, 0x3d, 0x31}
        	            	actual  : types.Tx{0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2d, 0x30, 0x30, 0x30, 0x2d, 0x30, 0x3d, 0x33, 0x30, 0x3d, 0x31}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	 (types.Tx) (len=17) {
        	            	- 00000000  73 65 6e 64 65 72 2d 30  30 30 2d 30 3d 33 31 3d  |sender-000-0=31=|
        	            	+ 00000000  73 65 6e 64 65 72 2d 30  30 30 2d 30 3d 33 30 3d  |sender-000-0=30=|
        	            	  00000010  31                                                |1|
        	Test:       	TestTxPool_BroadcastQueue
```

### PR DESCRIPTION
**Pull request by tropicaldog**
## Description
Closes #1261

### CODE REVIEW

**Review by rootulp — COMMENTED** [review]
I can't get the flake to reproduce locally before or after this change. @tropicaldog do you mind explaining why this fixes the flake?

**Comment by tropicaldog** [comment]
@rootulp I think the original code might lead to a race condition, where the goroutine may start consuming transactions before all of them are added. Using time.Sleep(10 * time.Millisecond) to introduce a delay is not a reliable solution imo.
The command I use to reproduce the flaky behavior is:
`go test -timeout 30s -run ^TestTxPool_BroadcastQueue$ github.com/cometbft/cometbft/mempool/cat -race -count 10`
Interestingly, the flaky behavior only occurs on my M2 Mac, where the test fails 50% of the time. When I tried running the same command on Ubuntu 22.04 PC, no flakiness was observed.

**Review by rootulp — APPROVED** [review]
Thanks for the explanation! I'm on an M1 Mac and the test is still passing on my machine after your fix so LGTM.

**Review by rach-id — APPROVED** [review]
unable to reproduce the flake locally on Mac, but this fix looks reasonable to me. There is no need to wait to introduce the delay where we can just broadcast all the transactions before starting to consume them

**Review by evan-forbes — APPROVED** [review]
thanks @tropicaldog

**Review by rootulp — APPROVED** [review]

**Comment by evan-forbes** [comment]
@tropicaldog we have to update this branch by merging main, perhaps you could give one of us perms to do that on your fork so we could merge this? either that, or you will have to merge main again :sweat_smile:

**Comment by tropicaldog** [comment]
> @tropicaldog we have to update this branch by merging main, perhaps you could give one of us perms to do that on your fork so we could merge this? either that, or you will have to merge main again 😅

Yeah I guess I didn't have enough permission. Anyway I will merge main now, thanks for your reviews!

**Pull request merged**
