### PR TITLE
feat(mempool): add metric size of pool in bytes

### PR DESCRIPTION
**Pull request by hoank101**
This PR exposes a new metric SizeBytes for the total size of the mempool in bytes. We already keep track of this value internally, in the variable txsBytes. Currently there is the metric Size for the size of the mempool in number of transactions.

### CODE REVIEW

**Review by rootulp — APPROVED** [review]
Overall this makes sense to me. 

1. @hoank101 what motivated this PR? Is there a Github issue we can link in the PR description?
2. Should we submit a similar PR upstream in CometBFT?
3. I modified the PR title to conform to conventional commits.

**Comment by hoank101** [comment]
> Overall this makes sense to me.
> 
> 1. @hoank101 what motivated this PR? Is there a Github issue we can link in the PR description?
> 2. Should we submit a similar PR upstream in CometBFT?
> 3. I modified the PR title to conform to conventional commits.

thank you, PR is already in CometBFT, I think it is missing in your chan, will help monitor metrics

**Comment by rootulp** [comment]
> PR is already in CometBFT

Thanks! I found https://github.com/cometbft/cometbft/pull/1512

**Comment by hoank101** [comment]
can you merge it @evan-forbes @cmwaters ?

**Review by cmwaters — APPROVED** [review]
LGTM

**Review by staheri14 — APPROVED** [review]
Looks good!

**Pull request merged**
