### PR TITLE
test: messages surpassing MConnection's receiving buffer capacity are dropped

### LINKED ISSUE #1162: Profile, benchmark, and add more load tests for portions of the p2p stack
The [MConnection](https://github.com/celestiaorg/celestia-core/blob/96dd1cf20aef821c244f1d921bf5d249a4f3e27d/p2p/conn/connection.go#L78) is used as a final queue for all incoming and outgoing packets. For this reason, it seems at least within the realm of possibility that it plays a role of what I refer to as "The Syndrome", which is when we see validators unable to reach consensus despite bandwidth or compute limitations not being hit.

To better understand if the `MConnection` is playing a role in events that trigger "The Syndrome", such as the inscription events a few weeks ago, we should create simple load unit tests/benchmarks, while also profiling these benchmarks to see if there are any unexpected effective mutexes. The same goes for other low level transport logic, such as the [MultiplexTransport](https://github.com/celestiaorg/celestia-core/blob/570aa7ed3b1b309b7c249562a9e034a48ad823f6/p2p/transport.go#L138).

### PR DESCRIPTION
**Pull request by staheri14**
Addresses the first item of #1190
Closes #1162

### CODE REVIEW

**Comment by staheri14** [comment]
There is a race condition in the test that I am investigating. Will mark the PR ready for review as soon as I resolve the race issue.

**Review by rootulp — APPROVED** [review]

**Review by cmwaters — APPROVED** [review]
LGTM

This makes me think that it would be good to track everytime a message was dropped because it wasn't able to be added to the queue

I guess given that it would block for 10 seconds we'd notice if this were happening in production (right?)

**Comment by staheri14** [comment]
> I guess given that it would block for 10 seconds we'd notice if this were happening in production (right?)

Could you clarify the origin of the 10 seconds duration? 
Detection of this situation would be doable by inspecting the [logs](https://github.com/celestiaorg/celestia-core/blob/938fb01ccbf0b9ac0f270fe5d6f9ce6b2aad7ab6/p2p/conn/connection.go#L861).  
Another sign is when the receiving peer disconnects the sending peer, as shown in [these lines](https://github.com/celestiaorg/celestia-core/blob/938fb01ccbf0b9ac0f270fe5d6f9ce6b2aad7ab6/p2p/conn/connection.go#L638-L644). However, this behavior is not unique to this scenario.

**Comment by staheri14** [comment]
>This makes me think that it would be good to track everytime a message was dropped because it wasn't able to be added to the queue 

Added a tracking issue for your suggestion https://github.com/celestiaorg/celestia-core/issues/1223

**Pull request merged**
