### PR TITLE
chore(deps): upgrade to grpc-go v1.59.0

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/celestiaorg/celestia-core/issues/1127

I scanned [release notes](https://github.com/grpc/grpc-go/releases) between grpc-go v1.52.0 and v1.59.0 and couldn't find anything concerning but I'm not super familiar with this repo's usage of grpc-go features so I'm relying on CI to tell us if something broke via this upgrade.

### CODE REVIEW

**Comment by rootulp** [comment]
I tried explicitly setting a MaxConcurrentStreams in https://github.com/celestiaorg/celestia-core/pull/1128/commits/67640af1e93dcc60cedc13d6c21cf9795f2b0751 but reverted b/c it's not easily test-able.

**Comment by rootulp** [comment]
My recommendation is to bump to v.1.59.0 immediately (this PR) and then pull from upstream after https://github.com/cometbft/cometbft/issues/1546 has been handled.

**Review by SweeXordious — APPROVED** [review]
we're using the same version in the app also:

https://github.com/celestiaorg/celestia-app/blob/73942bf5b00d89dfeb77ea26881764f639a8d3db/go.mod#L23

So, I guess should be fine to bump. Deferring to others for final approval

**Review by evan-forbes — APPROVED** [review]

**Review by staheri14 — COMMENTED** [review]
With this modification, are we imposing a limit on `MaxConcurrentStreams`? Or does it default to `math.MaxUint32`? The unlimited number of streams doesn't sound necessary.

**Comment by rootulp** [comment]
This PR doesn't explicitly set `MaxConcurrentStreams` so I assume the server will continue to use the default of `math.MaxUint32`. I think we should wait until CometBFT explicitly sets a value there and then pull the change here.

**Review by cmwaters — APPROVED** [review]
Just FYI, we don't use gRPC here so this doesn't actually affect us. CometBFT uses grpc for two servers: 1) ABCI and 2) an RPC equivalent that only exposes `BroadcastTx` but is usually off and unknown to most users.

Since we run celestia-app in process we don't actually use gRPC here. The only case we should be concerned about is in the cosmos-sdk which I believe has already been bumped

**Comment by rootulp** [comment]
Unclear which requirement isn't met. The security/snyk thing always fails and isn't required.

Screenshot 2023-10-30 at 3 47 09 PM

**Review by staheri14 — APPROVED** [review]

**Comment by rootulp** [comment]
celestia-core test flakes are out of control 🤯

**Pull request merged**
