### PR TITLE
Consensus block propagation via IPFS

### PR DESCRIPTION
**Pull request by Wondertan**
Closes: #85

### CODE REVIEW

**Comment by Wondertan** [comment]
Current status:
- Maverick won't compile as it is supposed to be removed
- Consensus state tests are falling due to stack on RetreiveBlockData for some unobvious reason(Looking into this)

**Comment by liamsi** [comment]
> Maverick won't compile as it is supposed to be removed

@Wondertan this PR: https://github.com/lazyledger/lazyledger-core/pull/295 cherry-picks half the story of #292. But I think this is actually enough to unblock you with the above. We can deal with the remaining changes when we update to 0.35 IMO.

**Comment by liamsi** [comment]
@Wondertan can we close this PR?

**Comment by Wondertan** [comment]
Indeed, also I am sure even branch won't be needed.

**Pull request closed without merging**
