### PR TITLE
feat!: move evidence back to Tendermint block

### PR DESCRIPTION
**Pull request by rootulp**
Closes: https://github.com/celestiaorg/celestia-core/issues/894

The CI check proto-breakage is expected to fail ([here](https://github.com/celestiaorg/celestia-core/actions/runs/3568543909/jobs/5997530673#step:3:39)) because this PR makes breaking changes to the protobuf definitions.

### CODE REVIEW

**Comment by rootulp** [comment]
There is an issue with this test: https://github.com/rootulp/celestia-core/blob/2656054788d3923edf4839376d5a97f9c3a707ab/node/node_test.go#L225 which calls https://github.com/rootulp/celestia-core/blob/2656054788d3923edf4839376d5a97f9c3a707ab/node/node_test.go#L225. It looks like the amount of data in the proposal block exceeds `maxDataBytes`. This may be resolved by updating the calculation used to determine `maxDataBytes`.

**Review by evan-forbes — APPROVED** [review]
LGMT, we might need a tag for super-mega-breaking.

This looks like it was resolved after accounting for the varint plus ceasing to double the data, no?
> This may be resolved by updating the calculation used to determine maxDataBytes.
It's also possible the proxy app in the test isn't respecting the maxDataBytes param.

**Comment by rootulp** [comment]
> This looks like it was resolved after accounting for the varint plus ceasing to double the data, no?

Yep, resolved by reverting the celestia-core modifications to the mempool back to vanilla Tendermint in https://github.com/celestiaorg/celestia-core/pull/897/commits/a158519e2ec063d19a7fd9a6c30f2462a0683f71 and https://github.com/celestiaorg/celestia-core/pull/897/commits/34fa0fd7fce79f529c588ee30ced63df5a423d00. I just marked the comment as resolved.

**Comment by rootulp** [comment]
> LGMT, we might need a tag for super-mega-breaking.

Agreed. I just created and added the label "proto breaking". I infer that a celestia-app release with this change won't be compatible with existing testnets so we may need a strategy meeting on how to upgrade all testnets after we cut a celestia-app release with this change.

**Pull request merged**
