### PR TITLE
Pull changes from upstream v0.35.x

### PR DESCRIPTION
**Pull request by evan-forbes**
This PR pulls the most recent changes from upstream that have been merged into v0.35.x. Note that this goes a commits beyond v0.35.5.

Huge shout out to the tendermint team for these
Closes #774

### CODE REVIEW

**Review by liamsi — COMMENTED** [review]
> Note that this goes a commits beyond v0.35.5.

should we wait for the tendermint team to cut v0.35.6? Or do you think it's worth having that unreleased version for now?

**Comment by evan-forbes** [comment]
> should we wait for the tendermint team to cut v0.35.6? Or do you think it's worth having that unreleased version for now?

that's a good question, I'm not 100% certain, but these involve two changes that were made after looking at data from mamaki, and I think we should at least test them. Perhaps we should add them in a different PR so if they are causing issues for whatever reason we can revert them easier?

https://github.com/tendermint/tendermint/commit/e8ac37223fae22eef27c178a25bf2beed28280e0

https://github.com/tendermint/tendermint/commit/a889f17e5134c9ab738ab2c0b40a6f7f4da77538

**Comment by evan-forbes** [comment]
The new commits also fix this issue, which is particularly relevant to networked with a mix of legacy and new p2p stacks 
https://github.com/tendermint/tendermint/issues/8662

**Review by adlerjohn — APPROVED** [review]

**Comment by evan-forbes** [comment]
Let's actually hold off on this until https://github.com/tendermint/tendermint/pull/8684 as it enables us to not use the legacy p2p stack. Then I think we're ready to push a new release and ask folks to upgrade

**Review by adlerjohn — APPROVED** [review]

**Pull request merged**
