### PR TITLE
chore: remove repetitive words

### PR DESCRIPTION
**Pull request by toofooboo**
remove repetitive words

### CODE REVIEW

**Review by rootulp — APPROVED** [review]
Thanks! Some of these repetitive words may exist upstream in https://github.com/cometbft/cometbft so you could submit a similar PR there.

**Comment by evan-forbes** [comment]
closing as we should address upstream

thanks for this @toofooboo

**Comment by ultratwo** [comment]
> > this is an airdrop typo farmer. please do not merge.
> > [FuelLabs/sway#5880](https://github.com/FuelLabs/sway/pull/5880) [celestiaorg/celestia-node#3320](https://github.com/celestiaorg/celestia-node/pull/3320)
> 
> No. i am a real person..

You're a real person airdrop farming typos. Have a bit of shame.

**Comment by evan-forbes** [comment]
I think the best approach here is to move things upstream in https://github.com/cometbft/cometbft

this keeps diff minimal while fixing the issue for us and all future projects

**Pull request closed without merging**
