### PR TITLE
fix: add an option to specify a config when starting a test rpc node

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

This PR adds an option to the tendermint test helper rpc nodes so that we can specify an exact configuration that we want.

This addition was optimized to minimize the diff between this fork and upstream, not necessarily the ideal solution. 

Closes: #XXX

### CODE REVIEW

**Review by distractedm1nd — CHANGES_REQUESTED** [review]
We also need `StartTendermint`, which takes `...func(*Options)`. This would be fine if we could pass in a function that sets the config, but the option fields aren't exported so we cannot set them. Would changing the signature of `StartTendermint` to include a `cfg` cause too big of a diff?

**Comment by evan-forbes** [comment]
> the option fields aren't exported so we cannot set them. Would changing the signature of StartTendermint to include a cfg cause too big of a diff?

The diff is definitely doable, as simply adding a field isn't difficult even if this function is used in a few places (6 total), but its just slightly less ideal as we have to fix that change every time we upgrade. Figured we could take advantage of the options since they already exist and hopefully have less of a diff.

just exported the `SpecificConfig` field, that _should_ essentially be the same as add an argument specifically for it, but if this doesn't work we'll just add the arg.

**Comment by rootulp** [comment]
For other reviewers, motivation for this PR was in Slack:

> We need either `globalConfig` global var to be exported or we need the ability to pass an RPC listen addr to https://github.com/celestiaorg/celestia-core/blob/v0.34.x-celestia/rpc/test/helpers.go#L119 so that we can override the rpc listen address (otherwise our swamp tests cannot work)

**Review by rootulp — APPROVED** [review]
[no change needed] an alternative approach may be to add an `rpcAddress` option to upstream [here](https://github.com/tendermint/tendermint/blob/main/rpc/test/helpers.go#L27-L30) so that our fork does not diverge from upstream. However I expect the proposed approach is likely slower to get reviewed, merged, and usable by celestia-core.

**Review by SweeXordious — APPROVED** [review]

**Review by distractedm1nd — CHANGES_REQUESTED** [review]

**Review by distractedm1nd — APPROVED** [review]
Works great! Thanks

**Pull request merged**
