### PR TITLE
Implement metric for rejected `ProcessProposal`

### PR DESCRIPTION
**Pull request by rootulp**
Resolves https://github.com/celestiaorg/celestia-core/issues/803
Supercedes https://github.com/celestiaorg/celestia-core/pull/808

## TODO
- [x] unit tests
    - [x] option A: [prior art](https://github.com/rootulp/celestia-core/blob/76ebb889c5cbe47013f2c65db67e56d9694b5f16/p2p/switch_test.go#L396-L413)
    - [ ] option B: [prometheus/testutil](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/testutil)
- [ ] ~~manually verify metric is emitted~~ skipping b/c manual testing seems non-trivial. If necessary explore https://github.com/celestiaorg/celestia-app/blob/main/contrib/single-node.sh

### CODE REVIEW

**Comment by evan-forbes** [comment]
is this ready for review? it looks finished to me I think

**Comment by rootulp** [comment]
Apologies, this is not ready for review yet. I would like to tackle the TODO tasks in PR description prior to moving this from draft to ready for review.

**Comment by rootulp** [comment]
@evan-forbes ready for review

**Review by evan-forbes — APPROVED** [review]
great work testing this stuff!

**Pull request merged**
