### PR TITLE
Remove the counter application

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

pull changes from upstream to help fix the app_tests test

### CODE REVIEW

**Review by liamsi — APPROVED** [review]
I want to keep the diff to tendermint minimal ideally. But removing code makes things easier. So LGTM

**Comment by evan-forbes** [comment]
the test is still failing, so I will continue to debug this here, and also fix the linter before we merge

**Comment by adlerjohn** [comment]
Can I close?

**Comment by evan-forbes** [comment]
yes, definitely

**Pull request closed without merging**
