### PR TITLE
feat!: increase MaxBlockSizeBytes to 128 MiB (backport #1289)

### PR DESCRIPTION
**Pull request by staheri14**
Manual backport of PR https://github.com/celestiaorg/celestia-core/pull/1289

### CODE REVIEW

**Review by rootulp — COMMENTED** [review]
Why are we backporting this breaking change to the v0.34.x-celestia branch? 
- Do we plan on releasing it in a v1.x release of this repo?
- Do we plan on including this in a celestia-app v1.x release or only in v2.x?

Taking a step back: what's the point of `main` if we're backporting breaking changes?

**Comment by staheri14** [comment]
> * g it in a v1.x release of this repo?

I have already stated my pov on this in the slack channel and am in favour of not back-porting breaking changes (including the current PR) to the `v0.34.x-celestia`, however, as we didn't get to any conclusion about the branch management, I figured to open this PR and get team's opinion by approving or disapproving of this PR.

**Comment by cmwaters** [comment]
> Taking a step back: what's the point of main if we're backporting breaking changes?

The original intended purpose of main was to match ABCI methods with mainline SDK so we could unfork ourselves and run vanilla v0.47.x. This ended up not happening because it was more complex than we intended. We are now planning to attempt this again for v3 (with v0.50 or v0.52 of the SDK). We are probably better equipped for this now we have the single binary syncs figured out. 

I also thought that celestia-core wouldn't be making any breaking changes from v1 to v2 and thus was okay with leaving the branches as is. So with that in mind we can do the following:

1. Use `main` for `v2` (involves modifying our SDK to match the ABCI methods in `main`) <- would prefer not to do this
2. Branch off `v0.34.x-celestia` with a new branch that is targeting `v2` (thus we would have three branches in total) <- not sure about this
3. Simply backport this breaking change as it's the only one we intend to do and it's unlikely that v2 will ever reach past 100MB blocks.
4. Don't merge this change as it's probably not necessary to have.

**Comment by evan-forbes** [comment]
managing three different branches here would be a pain, however if we're maintaining three different versions of code with different breaking changes, then that doesn't seem unreasonable. the branch that app v1 relies on wouldn't have to be maintained for long I don't think.

for this specific change, I'm not super worried about it. as suggested earlier, we might get more benefit out of this if we just increase this value to something even larger. Either that, or as mentioned above, we simply don't merge this change since a network test with 100MB is good enough in most cases.

**Comment by rootulp** [comment]
Thanks Callum for the context. IMO the release branches in this repo should be tied to celestia-core major releases _not_ celestia-app releases. I propose:
1. https://github.com/celestiaorg/celestia-core/issues/1305
2. Renaming `main` to something like `experimental-unfork`
3. Modifying the default branch in this repo to be `v1.x`

After those changes, all PRs by default should target `v1.x`. To handle the two in-flight PRs that I think are breaking:
1. https://github.com/celestiaorg/celestia-core/pull/1290 modify this to not be breaking by adding config instead of modifying the existing config
2. (this PR) seems like we don't _need_ it.

After all of that, we only have to maintain one branch and that branch is v1.x

**Comment by staheri14** [comment]
> Simply backport this breaking change as it's the only one we intend to do and it's unlikely that v2 will ever reach past 100MB blocks.

If we aim to support a maximum block size of `100 MiB` in v.1, it's necessary to merge this PR. 
Below is the reason:
The maximum block size correlates with the square size, based on the relationship in the formula provided [here](https://github.com/celestiaorg/celestia-app/blob/d231bdca4ba84b79dddfd146967be96515d9e176/pkg/appconsts/initial_consts.go#L14):

- Square size: 64 → Max block size = 1,974,272 bytes (~1.88 MiB)
- Square size: 128 → Max block size = 7,897,088 bytes (~7.5 MiB)
- Square size: 256 → Max block size = 31,588,352 bytes (~30 MiB)
- Square size: 512 → Max block size = 126,343,508 bytes (~120 MiB)

To support a `100 MiB` block, we would need to accommodate a maximum square size of `512`. This requires updating `GovMaxSquareSize` to `512` (an other square size related consts), resulting in a `MaxBytes`/maximum block size of `126,343,508` bytes. This size exceeds the current hardcoded `MaxBlockSizeBytes` limit of `104,857,600` bytes in the consensus layer and would be rejected. Consequently, the next smaller maximum square size would be `256`, which allows for a maximum block size of only `30 MiB`. 
Hence, we either allow block size of 30MiB, or 100MiB, but nothing in between.

**Comment by rootulp** [comment]
> If we aim to support a maximum block size of 100 MiB in v.1

Are you referring to celestia-core v1 or celestia-app v1?

**Comment by staheri14** [comment]
> Are you referring to celestia-core v1

I am referring to the celestia-core v1 (`v0.34.x-celestia`), and any version of the celestia-app that depends on it.

**Comment by rootulp** [comment]
Thanks! Then I agree, we need to merge this PR if we need to support bigger blocks in celestia-core v1.x releases. My immediate reaction is _why_ do we need to support bigger blocks in celestia-core v1.x releases? If we backport this change we're violating SemVer so we should update [this section](https://github.com/celestiaorg/celestia-core?tab=readme-ov-file#versioning).

**Comment by staheri14** [comment]
>After all of that, we only have to maintain one branch and that branch is v1.x

But to host breaking changes and to comply by SemVer, another branch i.e., v2 needs to exist, right?

**Comment by staheri14** [comment]
Can we have two core branches (inspired by @rootulp proposal)
- `v.1` which would replace the `main` and `v0.34.x`
- `v.2` mirrors `v.1` and hosts breaking changes to `v.1`
In the celestia-app side, we can point to either core `v1` or core `v2`, depending on which branch results in a major version bump in the celestia-app. I think since the breaking changes in the core `v.2` (the tracing and the block size `128MiB`) do not result in breaking changes in the app, then we can easily make celestia-app latest version depend on core v.2.

**Comment by evan-forbes** [comment]
> Hence, we either allow block size of 30MiB, or 100MiB, but nothing in between

why can't we have things imbetween? I could be wrong but afaiu this would work with the current implementation.

> Can we have two core branches 

I'm also perfectly okay with splitting v0.34.x into two branches. However does this include stopping our maintence of main (v3)?

**Comment by staheri14** [comment]
> why can't we have things imbetween? I could be wrong but afaiu this would work with the current implementation.

It is because of how parameters are set and verified in celestia-app and celestia-core:
Celestia-app sets `MaxBytes` based on `GovMaxSquareSize`, then the calculated `MaxBytes` is compared against the celestia-core's const `MaxBlockSizeBytes`. 
If `GovMaxSquareSize` = `256`, then `MaxBytes`=`31,588,352` bytes -> will be less than celestia-core's const `MaxBlockSizeBytes`=`104,857,600` bytes hence will be accepted
If `GovMaxSquareSize` = `512`, then `MaxBytes`=`126,343,508` bytes -> will NOT be less than celestia-core's const `MaxBlockSizeBytes`=`104,857,600` bytes hence will be rejected

**Comment by staheri14** [comment]
Based on today's decision, I assume we are good to merge this PR. 
Please let me know if you think otherwise.

**Comment by rootulp** [comment]
In today's call, we agreed on big blocks merging breaking changes to a separate branch and punting the decision on merging breaking changes until after we investigate how difficult it is to cut a celestia-core v2.

**Comment by staheri14** [comment]
Closing the PR due to https://github.com/celestiaorg/celestia-core/pull/1303#issuecomment-2072932944
Will reopen if we change direction in the future.

**Pull request closed without merging**
