### PR TITLE
chore: Pull latest v0.35.x

### PR DESCRIPTION
**Pull request by evan-forbes**
pulls the latest upstream changes. Includes the latest p2p changes that will be included in v0.35.7

### CODE REVIEW

**Comment by evan-forbes** [comment]
I tried this out on mamaki, and it was failing to sign blocks so converting to a draft for now.

**Comment by evan-forbes** [comment]
ok, so weirdly enough the actual cause was reporting the gas values in the sdk https://github.com/celestiaorg/cosmos-sdk/pull/192 and these changes seem to work fine, so I'm marking these ready for review

**Review by adlerjohn — APPROVED** [review]

**Comment by williambanfield** [comment]
Hey, this branch contains an unreleased patch in https://github.com/celestiaorg/celestia-core/commit/6f4ef729641e718515a785f728fcf867fd6653f6 that still needs a bit more testing. I'd recommend just pulling in up to the v0.35.7 tag.

**Comment by evan-forbes** [comment]
closing as tendermint v0.35 has officially been discontinued

**Pull request closed without merging**
