### PR TITLE
Add ability to remove "Parent" transactions from the mempool

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

For problem statement, please see #581. This PR introduces a wrapper around the `types.Tx` type to attach the hash of the "parent" transaction, in this case of the `WirePayForMessage`, so that after the "child" transaction is confirmed, the parent can easily be removed from the mempool.

There are some meaningful downsides to this approach, mainly that we add an extra hash to each `PayForMessage` transaction that gets included in the block, and that we add a small amount of overhead when checking for wrapper. Unfortunately, the way that the mempool is currently designed requires the hash of the transaction in order to be removed.

This PR also requires a PR to be made in the app that modifies the transaction decoder to unwrap these transactions, along with wrapping them during the Preprocess step

### CODE REVIEW

**Review by liamsi — COMMENTED** [review]
The trajectory looks good. I'm just wondering how this works in abci++ in general? I mean the Block.Data can be modified arbitrarily there. So there should be a way without modifying tendermint if I am not mistaken.

**Comment by evan-forbes** [comment]
AFAICT, all transactions are referenced using their hashes, so we will have to have the hash of the parent WirePayForMessage somehow.
https://github.com/tendermint/tendermint/blob/53565cb815e2d04343818c9cff38ed108f234c2b/internal/mempool/v0/clist_mempool.go#L341

We have the alternative to manage the hashes another way, which I think is preferable, as we won't include an extra hash in each PayForMessage tx

**Comment by evan-forbes** [comment]
This solution is working, but we should use something else after devnet. In theory, this shouldn't be an issue, as the transactions in the mempool are rechecked by default, and therefore should be removed as they have the same nonce as the PayForMessage tx that is getting confirmed. They aren't being removed though, and I'm still unsure as to why.

**Review by liamsi — APPROVED** [review]
devnetooooooor

**Review by adlerjohn — APPROVED** [review]

**Pull request merged**
